### PR TITLE
Why not include specialReports too?

### PR DESCRIPTION
**Pull request by georgecrawford**

### CODE REVIEW

**Comment by i-like-robots** [comment]
Poor special reports... this may create typeahead duplicates if the bertha spreadsheet used by the search API also includes special reports.

**Comment by georgecrawford** [comment]
Would they not be caught by the dedupe? https://github.com/Financial-Times/next-tme-search-api/blob/master/server/controllers/suggestions.js#L34-L39

**Comment by i-like-robots** [comment]
Hopefully! I forgot about that (we added it some time later)

**Comment by georgecrawford** [comment]
Happy to merge then? Then what - wait for complaints about clashes?

**Comment by i-like-robots** [comment]
Go ahead, I wouldn't worry about it being an issue (and we have access to the spreadsheet anyhoo)

**Pull request merged**
